<?php

namespace FreshMail;

use ArrayObject;
use Exception;

class SubscriberCollection extends ArrayObject
{

    public function append($value)
    {
        if ($value instanceof Subscriber) {
            parent::append($value); // TODO: Change the autogenerated stub
        } else {
            throw new Exception('value isn\'t Subscriber class');
        }
    }

}