version: '3.9'




services:
    mariadb:
        image: mariadb
        container_name: prestashop-db
        restart: always
        environment:
            MARIADB_DATABASE: prestashop
            MARIADB_ROOT_PASSWORD: prestashop
        ports:
            - 3306:3306
        networks:
            - prestashop
        volumes:
            - ./mariadb:/var/lib/mysql

            
    prestashop:
        image: prestashop/prestashop:1.7
        container_name: prestashop
        environment:
            DB_SERVER: mariadb
        ports:
            - 8080:80
        networks:
            - prestashop
        volumes:
            - ./webshop:/var/www/html
                    
networks:
    prestashop:
    
