version: '3.9'




services:
    mariadb:
        image: mariadb
        container_name: prestashop-db
        restart: always
        environment:
            MARIADB_DATABASE: prestashop
            MARIADB_ROOT_PASSWORD: prestashop
        ports:
            - 3306:3306
        networks:
            - prestashop
        volumes:
            - ./mariadb:/var/lib/mysql

            
    prestashop:
        container_name: prestashop
        environment:
            DB_SERVER: mariadb
            PS_DOMAIN: localhost:8080
            PS_DOMAIN_SSL: localhost:8081
        ports:
            - 8080:80
            - 8081:443
        build: .
        networks:
            - prestashop
        volumes:
            - ./webshop:/var/www/html
                    
networks:
    prestashop:
    
