services:
  _defaults:
    public: true

  FreshMail.Service.Form:
    class: FreshMail\Service\FormService
    arguments:
      - '@FreshMail_Repository_Form'
    public: true

  FreshMail_Repository_Form:
    class: FreshMail\Repository\FormRepository
    public: true