<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6209d2cc1bb420288929f962f08a3ac7
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FreshMail\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FreshMail\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'AbandonCartDiscount' => __DIR__ . '/../..' . '/src/Interface/AbandonCartDiscount.php',
        'AdminFreshmailAbandonedCartConfigController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailAbandonedCartConfig.php',
        'AdminFreshmailAjaxController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailAjax.php',
        'AdminFreshmailBaseController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailBase.php',
        'AdminFreshmailBirthdayController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailBirthday.php',
        'AdminFreshmailConfigController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailConfig.php',
        'AdminFreshmailDashboardController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailDashboardController.php',
        'AdminFreshmailFollowUpController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailFollowUp.php',
        'AdminFreshmailFormConfigController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailFormConfig.php',
        'AdminFreshmailProductNotificationController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailProductNotification.php',
        'AdminFreshmailProductNotificationListController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailProductNotificationList.php',
        'AdminFreshmailSubscribersController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailSubscribers.php',
        'AdminFreshmailWizardController' => __DIR__ . '/../..' . '/controllers/admin/AdminFreshmailWizardController.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FreshMail\\Customer' => __DIR__ . '/../..' . '/classes/Customer.php',
        'FreshMail\\Discount\\AbstractDiscount' => __DIR__ . '/../..' . '/classes/discount/AbstractDiscount.php',
        'FreshMail\\Discount\\Custom' => __DIR__ . '/../..' . '/classes/discount/Custom.php',
        'FreshMail\\Discount\\None' => __DIR__ . '/../..' . '/classes/discount/None.php',
        'FreshMail\\Discount\\Percent' => __DIR__ . '/../..' . '/classes/discount/Percent.php',
        'FreshMail\\Entity\\AsyncJob' => __DIR__ . '/../..' . '/src/Entity/AsyncJob.php',
        'FreshMail\\Entity\\Birthday' => __DIR__ . '/../..' . '/src/Entity/Birthday.php',
        'FreshMail\\Entity\\Cart' => __DIR__ . '/../..' . '/src/Entity/Cart.php',
        'FreshMail\\Entity\\CartNotify' => __DIR__ . '/../..' . '/src/Entity/CartNotify.php',
        'FreshMail\\Entity\\Email' => __DIR__ . '/../..' . '/src/Entity/Email.php',
        'FreshMail\\Entity\\EmailTemplate' => __DIR__ . '/../..' . '/src/Entity/EmailTemplate.php',
        'FreshMail\\Entity\\EmailToSynchronize' => __DIR__ . '/../..' . '/src/Entity/EmailToSynchronize.php',
        'FreshMail\\Entity\\EmailsSynchronized' => __DIR__ . '/../..' . '/src/Entity/EmailsSynchronized.php',
        'FreshMail\\Entity\\FollowUp' => __DIR__ . '/../..' . '/src/Entity/FollowUp.php',
        'FreshMail\\Entity\\Form' => __DIR__ . '/../..' . '/src/Entity/Form.php',
        'FreshMail\\Entity\\ProductNotification' => __DIR__ . '/../..' . '/src/Entity/ProductNotification.php',
        'FreshMail\\FollowUps' => __DIR__ . '/../..' . '/classes/FollowUps.php',
        'FreshMail\\Freshmail' => __DIR__ . '/../..' . '/classes/Freshmail.php',
        'FreshMail\\FreshmailApiV3' => __DIR__ . '/../..' . '/classes/FreshmailApiV3.php',
        'FreshMail\\FreshmailCode' => __DIR__ . '/../..' . '/classes/FreshmailCode.php',
        'FreshMail\\FreshmailList' => __DIR__ . '/../..' . '/classes/FreshmailList.php',
        'FreshMail\\Hooks' => __DIR__ . '/../..' . '/classes/Hooks.php',
        'FreshMail\\HooksForms' => __DIR__ . '/../..' . '/classes/HooksForms.php',
        'FreshMail\\Installer' => __DIR__ . '/../..' . '/classes/installer/Installer.php',
        'FreshMail\\Installer\\InstallerFactory' => __DIR__ . '/../..' . '/classes/installer/InstallerFactory.php',
        'FreshMail\\Installer\\Tabs' => __DIR__ . '/../..' . '/classes/installer/Tabs.php',
        'FreshMail\\Interfaces\\Installer' => __DIR__ . '/../..' . '/interfaces/Installer.php',
        'FreshMail\\Interfaces\\Sender' => __DIR__ . '/../..' . '/src/Interface/Sender.php',
        'FreshMail\\Interfaces\\TransactionEmail' => __DIR__ . '/../..' . '/src/Interface/TransactionEmail.php',
        'FreshMail\\ProductNotifications' => __DIR__ . '/../..' . '/classes/ProductNotifications.php',
        'FreshMail\\Repository\\AbstractRepository' => __DIR__ . '/../..' . '/src/Repository/AbstractRepository.php',
        'FreshMail\\Repository\\AsyncJobs' => __DIR__ . '/../..' . '/src/Repository/AsyncJobs.php',
        'FreshMail\\Repository\\Birthdays' => __DIR__ . '/../..' . '/src/Repository/Birthdays.php',
        'FreshMail\\Repository\\Carts' => __DIR__ . '/../..' . '/src/Repository/Carts.php',
        'FreshMail\\Repository\\EmailToSynchronize' => __DIR__ . '/../..' . '/src/Repository/EmailToSynchronize.php',
        'FreshMail\\Repository\\EmailsSynchronized' => __DIR__ . '/../..' . '/src/Repository/EmailsSynchronized.php',
        'FreshMail\\Repository\\FormRepository' => __DIR__ . '/../..' . '/src/Repository/FormRepository.php',
        'FreshMail\\Repository\\FreshmailAbandonCartSettings' => __DIR__ . '/../..' . '/src/Repository/FreshmailAbandonCartSettings.php',
        'FreshMail\\Repository\\FreshmailSettings' => __DIR__ . '/../..' . '/src/Repository/FreshmailSettings.php',
        'FreshMail\\Repository\\ProductNotifications' => __DIR__ . '/../..' . '/src/Repository/ProductNotifications.php',
        'FreshMail\\Repository\\Subscribers' => __DIR__ . '/../..' . '/src/Repository/Subscribers.php',
        'FreshMail\\Sender\\AbstractSender' => __DIR__ . '/../..' . '/classes/sender/AbstractSender.php',
        'FreshMail\\Sender\\Email' => __DIR__ . '/../..' . '/classes/sender/Email.php',
        'FreshMail\\Sender\\Factory' => __DIR__ . '/../..' . '/classes/sender/Factory.php',
        'FreshMail\\Sender\\FmSender' => __DIR__ . '/../..' . '/classes/sender/FmSender.php',
        'FreshMail\\Sender\\Legacy' => __DIR__ . '/../..' . '/classes/sender/Legacy.php',
        'FreshMail\\Sender\\Sender' => __DIR__ . '/../..' . '/classes/sender/Sender.php',
        'FreshMail\\Sender\\Service\\CartData' => __DIR__ . '/../..' . '/classes/sender/Service/CartData.php',
        'FreshMail\\Sender\\Service\\CartDataCollector' => __DIR__ . '/../..' . '/classes/sender/Service/CartDataCollector.php',
        'FreshMail\\Sender\\Service\\MockCartData' => __DIR__ . '/../..' . '/classes/sender/Service/MockCartData.php',
        'FreshMail\\Service\\AbandonCartService' => __DIR__ . '/../..' . '/src/Service/AbandonCartService.php',
        'FreshMail\\Service\\AccountService' => __DIR__ . '/../..' . '/src/Service/AccountService.php',
        'FreshMail\\Service\\AsyncJobService' => __DIR__ . '/../..' . '/src/Service/AsyncJobService.php',
        'FreshMail\\Service\\AuthService' => __DIR__ . '/../..' . '/src/Service/AuthService.php',
        'FreshMail\\Service\\BirthdayService' => __DIR__ . '/../..' . '/src/Service/BirthdayService.php',
        'FreshMail\\Service\\FollowUpService' => __DIR__ . '/../..' . '/src/Service/FollowUpService.php',
        'FreshMail\\Service\\FormService' => __DIR__ . '/../..' . '/src/Service/FormService.php',
        'FreshMail\\Service\\ProductNotificationService' => __DIR__ . '/../..' . '/src/Service/ProductNotificationService.php',
        'FreshMail\\Subscriber' => __DIR__ . '/../..' . '/classes/Subscriber.php',
        'FreshMail\\SubscriberCollection' => __DIR__ . '/../..' . '/classes/SubscriberCollection.php',
        'FreshMail\\Tools' => __DIR__ . '/../..' . '/classes/Tools.php',
        'FreshMail\\TransactionalEmail' => __DIR__ . '/../..' . '/classes/TransactionalEmail.php',
        'Freshmail\\Entity\\AbandonedCartSettings' => __DIR__ . '/../..' . '/src/Entity/AbandonedCartSettings.php',
        'Freshmail\\Entity\\FreshmailEmail' => __DIR__ . '/../..' . '/src/Entity/FreshmailEmail.php',
        'Freshmail\\Entity\\FreshmailSetting' => __DIR__ . '/../..' . '/src/Entity/FreshmailSetting.php',
        'freshmailRestoreModuleFrontController' => __DIR__ . '/../..' . '/controllers/front/restore.php',
        'freshmailajaxModuleFrontController' => __DIR__ . '/../..' . '/controllers/front/ajax.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6209d2cc1bb420288929f962f08a3ac7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6209d2cc1bb420288929f962f08a3ac7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6209d2cc1bb420288929f962f08a3ac7::$classMap;

        }, null, ClassLoader::class);
    }
}
